name: "tail -f My Scribbles"
url: http://soumyadipdm.github.io
description: My scribbles on interesting stuff on *nix, linux, devops, opensource

gems: [jekyll-paginate]
permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
